import { Platform } from 'react-native';
import ENV from 'react-native-config';
import { IMAGEKIT_URL, LEGAL_ENTITY_NAME, MAPBOX_ACCESS_TOKEN, GOOGLE_GEO_CODER_PLACE_API, CORS_PROXY_DISPATCHER_APP } from 'react-native-dotenv';

export const IS_WEB_PLATFORM = Platform.OS == 'web'

const Config = {
  IMAGEKIT_URL: IS_WEB_PLATFORM ? IMAGEKIT_URL : ENV.IMAGEKIT_URL,
  LEGAL_ENTITY_NAME: IS_WEB_PLATFORM ? LEGAL_ENTITY_NAME : ENV.LEGAL_ENTITY_NAME,
  MAPBOX_ACCESS_TOKEN: IS_WEB_PLATFORM ? MAPBOX_ACCESS_TOKEN : ENV.MAPBOX_ACCESS_TOKEN,
  GOOGLE_GEO_CODER_PLACE_API: IS_WEB_PLATFORM ? GOOGLE_GEO_CODER_PLACE_API : ENV.GOOGLE_GEO_CODER_PLACE_API,
  CORS_PROXY_DISPATCHER_APP: IS_WEB_PLATFORM ? CORS_PROXY_DISPATCHER_APP : ENV.CORS_PROXY_DISPATCHER_APP
}

export { Config };