// The generated stories are pinned to the matrix: a capability crossing C5
// (its cells turning final) makes this fail until the generator runs again,
// which is the point — Storybook shows every final cell, never a stale subset.
const fs = require('fs');
const { cells, CELL_STATE, NARRATED_ACTORS } = require('@jmstechnologiesinc/order-narration');

const { finalCells, render, storyName, OUT } = require('../../../scripts/genOrderCellStories');

describe('Order/OrderCells.stories.js — one story per final cell, generated', () => {
    it('is in sync with the matrix on disk', () => {
        expect(fs.readFileSync(OUT, 'utf8')).toBe(render(finalCells()));
    });
    it('covers exactly the final cells (83 today: 11 statuses × 5 verticals × 3 actors minus pending and N/A)', () => {
        const finals = cells().filter(({ cell }) => cell.state === CELL_STATE.final);
        expect(finalCells()).toHaveLength(finals.length);
        expect(finals.length).toBe(83);
        const names = finalCells().map(storyName);
        expect(new Set(names).size).toBe(names.length);
        for (const { actor } of finalCells()) expect(NARRATED_ACTORS).toContain(actor);
    });
    it('every generated story renders a view model with a label and no legacy status', () => {
        const source = fs.readFileSync(OUT, 'utf8');
        expect(source).not.toMatch(/(?<!CANONICAL_)ORDER_STATUS\./);
        expect(source).toMatch(/GENERATED by scripts\/genOrderCellStories\.js/);
    });
});
