import React from 'react';
import { View } from 'react-native';

import { setI18nConfig } from '../Localization/Localization';
import OrderTransitionButtons from './OrderTransitionButtons';
import OrderHistoryOrderItem from './OrderHistoryOrderItem';
import { orderViewModel } from './viewModel';

// GENERATED by scripts/genOrderCellStories.js from @jmstechnologiesinc/order-narration
// — one story per FINAL cell of the matrix (vertical × status × actor), 83
// today. Do not edit by hand: run the script; orderCellStories.test.js pins the
// file to the matrix. Order.stories.js keeps the hand-written stories (the
// variants, the pending capability, the chips and the buttons by tone).
setI18nConfig();

export default {
    title: 'packages/Order/cells',
};

// The five verticals of canon §7, as the three document fields `verticalOf`
// reads (platform, fulfillmentMethod, vendor.deliveryMethod) plus the driver
// that tells DOc from DOv.
const VERTICAL_FIXTURE = {
    DM: {
        platform: 'shopping',
        fulfillmentMethod: 'delivery',
        vendor: { title: 'Casa Nostra', deliveryMethod: 'Marketplace' },
        driver: { formattedName: 'Ana Ruiz', id: 'drv-1' },
    },
    DOc: {
        platform: 'shopping',
        fulfillmentMethod: 'delivery',
        vendor: { title: 'Casa Nostra', deliveryMethod: 'Own Staff' },
        driver: { formattedName: 'Ana Ruiz', id: 'drv-1' },
    },
    DOv: {
        platform: 'shopping',
        fulfillmentMethod: 'delivery',
        vendor: { title: 'Casa Nostra', deliveryMethod: 'Own Staff' },
        driver: null,
    },
    PU: {
        platform: 'shopping',
        fulfillmentMethod: 'pickup',
        vendor: { title: 'Casa Nostra', deliveryMethod: 'Marketplace' },
        driver: null,
    },
    RH: {
        platform: 'rideshare',
        fulfillmentMethod: 'delivery',
        vendor: null,
        driver: { formattedName: 'Ana Ruiz', id: 'drv-1' },
    },
};

const order = (vertical, status) => ({
    id: 'AB12345',
    status,
    author: { firstName: 'Marcos' },
    cart: { quantity: 3 },
    customerCost: [{ id: 'total', amount: 2775 }],
    preparation: { promisedReadyAt: '2026-09-13T18:42:00Z' },
    ...VERTICAL_FIXTURE[vertical],
});

const Cell = ({ vertical, status, actor }) => {
    const doc = order(vertical, status);
    const model = orderViewModel({ order: doc, actor });
    return (
        <View>
            <OrderHistoryOrderItem
                id={doc.id}
                title={model.headline ?? model.statusLabel}
                statusLabel={model.statusLabel}
                formattedTripStatus={model.detail}
                amount={doc.customerCost}
                chips={model.chips}
            />
            <OrderTransitionButtons actions={model.actions} onPress={() => {}} />
        </View>
    );
};

export const DM_placed_customer = () => <Cell vertical="DM" status="placed" actor="customer" />;
export const DM_placed_vendor = () => <Cell vertical="DM" status="placed" actor="vendor" />;
export const DM_confirmed_customer = () => <Cell vertical="DM" status="confirmed" actor="customer" />;
export const DM_confirmed_vendor = () => <Cell vertical="DM" status="confirmed" actor="vendor" />;
export const DM_ready_for_pickup_customer = () => <Cell vertical="DM" status="ready_for_pickup" actor="customer" />;
export const DM_ready_for_pickup_vendor = () => <Cell vertical="DM" status="ready_for_pickup" actor="vendor" />;
export const DM_awaiting_driver_customer = () => <Cell vertical="DM" status="awaiting_driver" actor="customer" />;
export const DM_awaiting_driver_vendor = () => <Cell vertical="DM" status="awaiting_driver" actor="vendor" />;
export const DM_driver_assigned_customer = () => <Cell vertical="DM" status="driver_assigned" actor="customer" />;
export const DM_driver_assigned_vendor = () => <Cell vertical="DM" status="driver_assigned" actor="vendor" />;
export const DM_driver_assigned_driver = () => <Cell vertical="DM" status="driver_assigned" actor="driver" />;
export const DM_driver_enroute_customer = () => <Cell vertical="DM" status="driver_enroute" actor="customer" />;
export const DM_driver_enroute_vendor = () => <Cell vertical="DM" status="driver_enroute" actor="vendor" />;
export const DM_driver_enroute_driver = () => <Cell vertical="DM" status="driver_enroute" actor="driver" />;
export const DM_completed_customer = () => <Cell vertical="DM" status="completed" actor="customer" />;
export const DM_completed_vendor = () => <Cell vertical="DM" status="completed" actor="vendor" />;
export const DM_completed_driver = () => <Cell vertical="DM" status="completed" actor="driver" />;
export const DM_cancelled_customer = () => <Cell vertical="DM" status="cancelled" actor="customer" />;
export const DM_cancelled_vendor = () => <Cell vertical="DM" status="cancelled" actor="vendor" />;
export const DM_cancelled_driver = () => <Cell vertical="DM" status="cancelled" actor="driver" />;
export const DM_vendor_rejected_customer = () => <Cell vertical="DM" status="vendor_rejected" actor="customer" />;
export const DM_vendor_rejected_vendor = () => <Cell vertical="DM" status="vendor_rejected" actor="vendor" />;
export const DM_no_driver_found_customer = () => <Cell vertical="DM" status="no_driver_found" actor="customer" />;
export const DM_no_driver_found_vendor = () => <Cell vertical="DM" status="no_driver_found" actor="vendor" />;
export const DOc_placed_customer = () => <Cell vertical="DOc" status="placed" actor="customer" />;
export const DOc_placed_vendor = () => <Cell vertical="DOc" status="placed" actor="vendor" />;
export const DOc_confirmed_customer = () => <Cell vertical="DOc" status="confirmed" actor="customer" />;
export const DOc_confirmed_vendor = () => <Cell vertical="DOc" status="confirmed" actor="vendor" />;
export const DOc_ready_for_pickup_customer = () => <Cell vertical="DOc" status="ready_for_pickup" actor="customer" />;
export const DOc_ready_for_pickup_vendor = () => <Cell vertical="DOc" status="ready_for_pickup" actor="vendor" />;
export const DOc_awaiting_driver_customer = () => <Cell vertical="DOc" status="awaiting_driver" actor="customer" />;
export const DOc_awaiting_driver_vendor = () => <Cell vertical="DOc" status="awaiting_driver" actor="vendor" />;
export const DOc_driver_assigned_customer = () => <Cell vertical="DOc" status="driver_assigned" actor="customer" />;
export const DOc_driver_assigned_vendor = () => <Cell vertical="DOc" status="driver_assigned" actor="vendor" />;
export const DOc_driver_assigned_driver = () => <Cell vertical="DOc" status="driver_assigned" actor="driver" />;
export const DOc_driver_enroute_customer = () => <Cell vertical="DOc" status="driver_enroute" actor="customer" />;
export const DOc_driver_enroute_vendor = () => <Cell vertical="DOc" status="driver_enroute" actor="vendor" />;
export const DOc_driver_enroute_driver = () => <Cell vertical="DOc" status="driver_enroute" actor="driver" />;
export const DOc_completed_customer = () => <Cell vertical="DOc" status="completed" actor="customer" />;
export const DOc_completed_vendor = () => <Cell vertical="DOc" status="completed" actor="vendor" />;
export const DOc_completed_driver = () => <Cell vertical="DOc" status="completed" actor="driver" />;
export const DOc_cancelled_customer = () => <Cell vertical="DOc" status="cancelled" actor="customer" />;
export const DOc_cancelled_vendor = () => <Cell vertical="DOc" status="cancelled" actor="vendor" />;
export const DOc_cancelled_driver = () => <Cell vertical="DOc" status="cancelled" actor="driver" />;
export const DOc_vendor_rejected_customer = () => <Cell vertical="DOc" status="vendor_rejected" actor="customer" />;
export const DOc_vendor_rejected_vendor = () => <Cell vertical="DOc" status="vendor_rejected" actor="vendor" />;
export const DOc_no_driver_found_customer = () => <Cell vertical="DOc" status="no_driver_found" actor="customer" />;
export const DOc_no_driver_found_vendor = () => <Cell vertical="DOc" status="no_driver_found" actor="vendor" />;
export const DOv_placed_customer = () => <Cell vertical="DOv" status="placed" actor="customer" />;
export const DOv_placed_vendor = () => <Cell vertical="DOv" status="placed" actor="vendor" />;
export const DOv_confirmed_customer = () => <Cell vertical="DOv" status="confirmed" actor="customer" />;
export const DOv_confirmed_vendor = () => <Cell vertical="DOv" status="confirmed" actor="vendor" />;
export const DOv_ready_for_pickup_customer = () => <Cell vertical="DOv" status="ready_for_pickup" actor="customer" />;
export const DOv_ready_for_pickup_vendor = () => <Cell vertical="DOv" status="ready_for_pickup" actor="vendor" />;
export const DOv_completed_customer = () => <Cell vertical="DOv" status="completed" actor="customer" />;
export const DOv_completed_vendor = () => <Cell vertical="DOv" status="completed" actor="vendor" />;
export const DOv_cancelled_customer = () => <Cell vertical="DOv" status="cancelled" actor="customer" />;
export const DOv_cancelled_vendor = () => <Cell vertical="DOv" status="cancelled" actor="vendor" />;
export const DOv_vendor_rejected_customer = () => <Cell vertical="DOv" status="vendor_rejected" actor="customer" />;
export const DOv_vendor_rejected_vendor = () => <Cell vertical="DOv" status="vendor_rejected" actor="vendor" />;
export const PU_placed_customer = () => <Cell vertical="PU" status="placed" actor="customer" />;
export const PU_placed_vendor = () => <Cell vertical="PU" status="placed" actor="vendor" />;
export const PU_confirmed_customer = () => <Cell vertical="PU" status="confirmed" actor="customer" />;
export const PU_confirmed_vendor = () => <Cell vertical="PU" status="confirmed" actor="vendor" />;
export const PU_ready_for_pickup_customer = () => <Cell vertical="PU" status="ready_for_pickup" actor="customer" />;
export const PU_ready_for_pickup_vendor = () => <Cell vertical="PU" status="ready_for_pickup" actor="vendor" />;
export const PU_completed_customer = () => <Cell vertical="PU" status="completed" actor="customer" />;
export const PU_completed_vendor = () => <Cell vertical="PU" status="completed" actor="vendor" />;
export const PU_cancelled_customer = () => <Cell vertical="PU" status="cancelled" actor="customer" />;
export const PU_cancelled_vendor = () => <Cell vertical="PU" status="cancelled" actor="vendor" />;
export const PU_vendor_rejected_customer = () => <Cell vertical="PU" status="vendor_rejected" actor="customer" />;
export const PU_vendor_rejected_vendor = () => <Cell vertical="PU" status="vendor_rejected" actor="vendor" />;
export const RH_confirmed_customer = () => <Cell vertical="RH" status="confirmed" actor="customer" />;
export const RH_awaiting_driver_customer = () => <Cell vertical="RH" status="awaiting_driver" actor="customer" />;
export const RH_driver_assigned_customer = () => <Cell vertical="RH" status="driver_assigned" actor="customer" />;
export const RH_driver_assigned_driver = () => <Cell vertical="RH" status="driver_assigned" actor="driver" />;
export const RH_driver_enroute_customer = () => <Cell vertical="RH" status="driver_enroute" actor="customer" />;
export const RH_driver_enroute_driver = () => <Cell vertical="RH" status="driver_enroute" actor="driver" />;
export const RH_completed_customer = () => <Cell vertical="RH" status="completed" actor="customer" />;
export const RH_completed_driver = () => <Cell vertical="RH" status="completed" actor="driver" />;
export const RH_cancelled_customer = () => <Cell vertical="RH" status="cancelled" actor="customer" />;
export const RH_cancelled_driver = () => <Cell vertical="RH" status="cancelled" actor="driver" />;
export const RH_no_driver_found_customer = () => <Cell vertical="RH" status="no_driver_found" actor="customer" />;
