#!/usr/bin/env node
'use strict';
// ADR-0017 §5.1 / plan §20.7 N2 tooling — ONE STORY PER FINAL CELL of the
// narration matrix, generated from the matrix itself so the stories can never
// lag behind it: when a capability's C5 turns its cells final, the next run of
// this script adds their stories and orderCellStories.test.js fails until it
// is run. Storybook wants named exports it can see statically, so the file is
// GENERATED and committed, never built at import time.
//
//   node scripts/genOrderCellStories.js          # rewrite src/Order/OrderCells.stories.js
//   node scripts/genOrderCellStories.js --check  # exit 1 if it drifts (the test does this)
const fs = require('fs');
const path = require('path');
const { cells, CELL_STATE } = require('@jmstechnologiesinc/order-narration');

const OUT = path.join(__dirname, '..', 'src', 'Order', 'OrderCells.stories.js');

const finalCells = () =>
    cells()
        .filter(({ cell }) => cell.state === CELL_STATE.final)
        .map(({ vertical, status, actor }) => ({ vertical, status, actor }));

const storyName = ({ vertical, status, actor }) => `${vertical}_${status}_${actor}`;

const render = (list) => {
    const header = `import React from 'react';
import { View } from 'react-native';

import { setI18nConfig } from '../Localization/Localization';
import OrderTransitionButtons from './OrderTransitionButtons';
import OrderHistoryOrderItem from './OrderHistoryOrderItem';
import { orderViewModel } from './viewModel';

// GENERATED by scripts/genOrderCellStories.js from @jmstechnologiesinc/order-narration
// — one story per FINAL cell of the matrix (vertical × status × actor), ${list.length}
// today. Do not edit by hand: run the script; orderCellStories.test.js pins the
// file to the matrix. Order.stories.js keeps the hand-written stories (the
// variants, the pending capability, the chips and the buttons by tone).
setI18nConfig();

export default {
    title: 'packages/Order/cells',
};

// The five verticals of canon §7, as the three document fields \`verticalOf\`
// reads (platform, fulfillmentMethod, vendor.deliveryMethod) plus the driver
// that tells DOc from DOv.
const VERTICAL_FIXTURE = {
    DM: { platform: 'shopping', fulfillmentMethod: 'delivery', vendor: { title: 'Casa Nostra', deliveryMethod: 'Marketplace' }, driver: { formattedName: 'Ana Ruiz', id: 'drv-1' } },
    DOc: { platform: 'shopping', fulfillmentMethod: 'delivery', vendor: { title: 'Casa Nostra', deliveryMethod: 'Own Staff' }, driver: { formattedName: 'Ana Ruiz', id: 'drv-1' } },
    DOv: { platform: 'shopping', fulfillmentMethod: 'delivery', vendor: { title: 'Casa Nostra', deliveryMethod: 'Own Staff' }, driver: null },
    PU: { platform: 'shopping', fulfillmentMethod: 'pickup', vendor: { title: 'Casa Nostra', deliveryMethod: 'Marketplace' }, driver: null },
    RH: { platform: 'rideshare', fulfillmentMethod: 'delivery', vendor: null, driver: { formattedName: 'Ana Ruiz', id: 'drv-1' } },
};

const order = (vertical, status) => ({
    id: 'AB12345',
    status,
    author: { firstName: 'Marcos' },
    cart: { quantity: 3 },
    customerCost: [{ id: 'total', amount: 2775 }],
    preparation: { promisedReadyAt: '2026-09-13T18:42:00Z' },
    ...VERTICAL_FIXTURE[vertical],
});

const Cell = ({ vertical, status, actor }) => {
    const doc = order(vertical, status);
    const model = orderViewModel({ order: doc, actor });
    return (
        <View>
            <OrderHistoryOrderItem
                id={doc.id}
                title={model.headline ?? model.statusLabel}
                statusLabel={model.statusLabel}
                formattedTripStatus={model.detail}
                amount={doc.customerCost}
                chips={model.chips}
            />
            <OrderTransitionButtons actions={model.actions} onPress={() => {}} />
        </View>
    );
};
`;
    const stories = list
        .map(
            (c) =>
                `export const ${storyName(c)} = () => <Cell vertical="${c.vertical}" status="${c.status}" actor="${
                    c.actor
                }" />;`
        )
        .join('\n');
    return `${header}\n${stories}\n`;
};

// Prettier 2 (synchronous) over the output, with the repository's config, so
// the generated file and `prettier --check` agree byte for byte.
const prettier = require('prettier');
const format = (code) => prettier.format(code, { ...(prettier.resolveConfig.sync(OUT) || {}), filepath: OUT });

const expected = format(render(finalCells()));
if (process.argv.includes('--check')) {
    const onDisk = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (onDisk !== expected) {
        console.error(
            `${path.relative(process.cwd(), OUT)} drifts from the matrix: run node scripts/genOrderCellStories.js`
        );
        process.exit(1);
    }
    console.log(`OrderCells.stories.js is in sync with the matrix (${finalCells().length} final cells)`);
} else {
    fs.writeFileSync(OUT, expected);
    console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${finalCells().length} stories`);
}

module.exports = { finalCells, render, format, storyName, OUT };
